#!/bin/sh

. /etc/templates/lib

tz=`kdb get sys_timezone`

if [ "$tz" == "0" ]; then
	echo "UTC"
else
	[ `kdb get sys_time_auto_switch` = "1" ] && echo "UTC${tz}UTC,M3.5.0/2,M10.5.0/3" || echo "UTC${tz}"
fi
