# Makefile for Sigrand MR17G module driver
# Written by Artem Y. Polyakov <artpol84@gmail.com>
# 01.09.2008

CFLAGS+=@CFLAGS@
obj-m := @DRVNAME@.o
@DRVNAME@-objs := mr17g_main.o mr17g_sci.o mr17g_net.o pef22554.o mr17g_sysfs.o mr17g_debug.o

@DRVNAME@.ko: mr17g_main.c mr17g_sci.c mr17g_net.c pef22554.c mr17g_sysfs.c mr17g_debug.c 
	make -C @KERNSRC@ SUBDIRS=$(PWD) modules CROSS_COMPILE=@CROSS_PREFIX@

all: @DRVNAME@.ko

install: @DRVNAME@.ko
	install -m 644 @DRVNAME@.ko @INST_PATH@/lib/modules/@KERNVER@/
	install -m 744 ./tools/mr17gcfg @INST_PATH@/sbin/@TOOLNAME@
	[ "yes" != "@DEBUG@" ] || install -m 744 ./tools/mr17g_debug @INST_PATH@/sbin/@DBGTOOLNAME@

clean:
	rm --preserve-root -f .*.o*
	rm --preserve-root -f .*.ko*
	rm --preserve-root -f *.o*
	rm --preserve-root -f *.ko*
	rm --preserve-root -f *.mod.*
	rm --preserve-root -f .mr17g*
	rm --preserve-root -f -R .tmp*


# Template for assembler debug
#mr16g_hdlc.s: mr16g_hdlc.c
#	make -C @KERNSRC@ CROSS_COMPILE=@CROSS_PREFIX@ $(PWD)/mr16g_hdlc.s
#debug: mr16g_hdlc.c mr16g_hdlc.s
#	@CROSS_PREFIX@objdump -d mr16g_hdlc.o > mr16g_hdlc.disasm

