CFLAGS+=@CFLAGS@
obj-m := @DRVNAME@.o
@DRVNAME@-objs := sg16lan.o

@DRVNAME@.ko: sg16lan.c
	make -C @KERNSRC@ SUBDIRS=$(PWD) modules CROSS_COMPILE=@CROSS_PREFIX@

all: @DRVNAME@.ko

install: @DRVNAME@.ko
	install -m 600 @DRVNAME@.ko @INST_PATH@/lib/modules/@KERNVER@
	install -m 700 ./tools/sg16cfg @INST_PATH@/sbin/@TOOLNAME@
	cp ./firmware/sg16.bin @INST_PATH@/lib/firmware/@DRVNAME@.bin

clean:
	rm --preserve-root -f .*.o*
	rm --preserve-root -f .*.ko*
	rm --preserve-root -f *.o*
	rm --preserve-root -f *.ko*
	rm --preserve-root -f *.mod.*
	rm --preserve-root -f .sg16*
	rm --preserve-root -f -R .tmp*



